/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class AnnIndex {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected AnnIndex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AnnIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JAVASPTAGJNI.delete_AnnIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AnnIndex(int p_dimension) {
    this(JAVASPTAGJNI.new_AnnIndex__SWIG_0(p_dimension), true);
  }

  public AnnIndex(String p_algoType, String p_valueType, int p_dimension) {
    this(JAVASPTAGJNI.new_AnnIndex__SWIG_1(p_algoType, p_valueType, p_dimension), true);
  }

  public void SetBuildParam(String p_name, String p_value, String p_section) {
    JAVASPTAGJNI.AnnIndex_SetBuildParam(swigCPtr, this, p_name, p_value, p_section);
  }

  public void SetSearchParam(String p_name, String p_value, String p_section) {
    JAVASPTAGJNI.AnnIndex_SetSearchParam(swigCPtr, this, p_name, p_value, p_section);
  }

  public boolean LoadQuantizer(String p_quantizerFile) {
    return JAVASPTAGJNI.AnnIndex_LoadQuantizer(swigCPtr, this, p_quantizerFile);
  }

  public void SetQuantizerADC(boolean p_adc) {
    JAVASPTAGJNI.AnnIndex_SetQuantizerADC(swigCPtr, this, p_adc);
  }

  public boolean BuildSPANN(boolean p_normalized) {
    return JAVASPTAGJNI.AnnIndex_BuildSPANN(swigCPtr, this, p_normalized);
  }

  public boolean BuildSPANNWithMetaData(byte[] p_meta, int p_num, boolean p_withMetaIndex, boolean p_normalized) {
    return JAVASPTAGJNI.AnnIndex_BuildSPANNWithMetaData(swigCPtr, this, p_meta, p_num, p_withMetaIndex, p_normalized);
  }

  public boolean Build(byte[] p_data, int p_num, boolean p_normalized) {
    return JAVASPTAGJNI.AnnIndex_Build(swigCPtr, this, p_data, p_num, p_normalized);
  }

  public boolean BuildWithMetaData(byte[] p_data, byte[] p_meta, int p_num, boolean p_withMetaIndex, boolean p_normalized) {
    return JAVASPTAGJNI.AnnIndex_BuildWithMetaData(swigCPtr, this, p_data, p_meta, p_num, p_withMetaIndex, p_normalized);
  }

  public BasicResult[] Search(byte[] p_data, int p_resultNum) { return JAVASPTAGJNI.AnnIndex_Search(swigCPtr, this, p_data, p_resultNum); }

  public BasicResult[] SearchWithMetaData(byte[] p_data, int p_resultNum) { return JAVASPTAGJNI.AnnIndex_SearchWithMetaData(swigCPtr, this, p_data, p_resultNum); }

  public BasicResult[] BatchSearch(byte[] p_data, int p_vectorNum, int p_resultNum, boolean p_withMetaData) { return JAVASPTAGJNI.AnnIndex_BatchSearch(swigCPtr, this, p_data, p_vectorNum, p_resultNum, p_withMetaData); }

  public boolean ReadyToServe() {
    return JAVASPTAGJNI.AnnIndex_ReadyToServe(swigCPtr, this);
  }

  public void UpdateIndex() {
    JAVASPTAGJNI.AnnIndex_UpdateIndex(swigCPtr, this);
  }

  public boolean Save(String p_saveFile) {
    return JAVASPTAGJNI.AnnIndex_Save(swigCPtr, this, p_saveFile);
  }

  public boolean Add(byte[] p_data, int p_num, boolean p_normalized) {
    return JAVASPTAGJNI.AnnIndex_Add(swigCPtr, this, p_data, p_num, p_normalized);
  }

  public boolean AddWithMetaData(byte[] p_data, byte[] p_meta, int p_num, boolean p_withMetaIndex, boolean p_normalized) {
    return JAVASPTAGJNI.AnnIndex_AddWithMetaData(swigCPtr, this, p_data, p_meta, p_num, p_withMetaIndex, p_normalized);
  }

  public boolean Delete(byte[] p_data, int p_num) {
    return JAVASPTAGJNI.AnnIndex_Delete(swigCPtr, this, p_data, p_num);
  }

  public boolean DeleteByMetaData(byte[] p_meta) {
    return JAVASPTAGJNI.AnnIndex_DeleteByMetaData(swigCPtr, this, p_meta);
  }

  public static AnnIndex Load(String p_loaderFile) {
    return new AnnIndex(JAVASPTAGJNI.AnnIndex_Load(p_loaderFile), true);
  }

  public static AnnIndex Merge(String p_indexFilePath1, String p_indexFilePath2) {
    return new AnnIndex(JAVASPTAGJNI.AnnIndex_Merge(p_indexFilePath1, p_indexFilePath2), true);
  }

}
