/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Edge {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Edge(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Edge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JAVASPTAGJNI.delete_Edge(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNode(int value) {
    JAVASPTAGJNI.Edge_node_set(swigCPtr, this, value);
  }

  public int getNode() {
    return JAVASPTAGJNI.Edge_node_get(swigCPtr, this);
  }

  public void setDistance(float value) {
    JAVASPTAGJNI.Edge_distance_set(swigCPtr, this, value);
  }

  public float getDistance() {
    return JAVASPTAGJNI.Edge_distance_get(swigCPtr, this);
  }

  public void setTonode(int value) {
    JAVASPTAGJNI.Edge_tonode_set(swigCPtr, this, value);
  }

  public int getTonode() {
    return JAVASPTAGJNI.Edge_tonode_get(swigCPtr, this);
  }

  public Edge() {
    this(JAVASPTAGJNI.new_Edge(), true);
  }

}
